spring:
  cloud:
    gateway:
      routes:

        # Policy API
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policies/**

        # Policy Swagger
        - id: policy-service-docs
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy-service/v3/api-docs
          filters:
            - RewritePath=/policy-service/(?<path>.*), /$\{path}

        # Customer API
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**

        # Customer Swagger
        - id: customer-service-docs
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/v3/api-docs
          filters:
            - RewritePath=/customer-service/(?<path>.*), /$\{path}

        # Claim API
        - id: claim-service
          uri: lb://CLAIM-SERVICE
          predicates:
            - Path=/claims/**

        # Claim Swagger
        - id: claim-service-docs
          uri: lb://CLAIM-SERVICE
          predicates:
            - Path=/claim-service/v3/api-docs
          filters:
            - RewritePath=/claim-service/(?<path>.*), /$\{path}

        # Auth API
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        # Auth Swagger
        - id: auth-service-docs
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/v3/api-docs
          filters:
            - RewritePath=/auth-service/(?<path>.*), /$\{path}




# spring:
#   cloud:
#     gateway:
#       routes:
#         - id: auth-service
#           uri: lb://AUTH-SERVICE
#           predicates:
#             - Path=/auth/**

#         - id: policy-service
#           uri: lb://POLICY-SERVICE
#           predicates:
#             - Path=/policies/**

#         - id: customer-service
#           uri: lb://CUSTOMER-SERVICE
#           predicates:
#             - Path=/customers/**

#         - id: claim-service
#           uri: lb://CLAIM-SERVICE
#           predicates:
#             - Path=/claims/**
# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG
