spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
         - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/api/policies/**
      

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
          # filters:
          #   - StripPrefix=2

        - id: claim-service
          uri: lb://CLAIM-SERVICE
          predicates:
            - Path=/claims/**

# spring:
#   application:
#     name: gateway

#   cloud:
#     gateway:
#       routes:
#         - id: policy-service
#           uri: lb://POLICY-SERVICE
#           predicates:
#             - Path=/policies/**
#           # filters:
#           #   - StripPrefix=1

#         - id: customer-service
#           uri: lb://CUSTOMER-SERVICE
#           predicates:
#             - Path=/customers/**
#           # filters:
#           #   - StripPrefix=1

#         - id: claim-service
#           uri: lb://CLAIM-SERVICE
#           predicates:
#             - Path=/claims/**
#           # filters:
#           #   - StripPrefix=1
