spring:
  cloud:
    gateway:
      routes:

        - id: policy-service
          uri: http://localhost:8082
          predicates:
            - Path=/policies/**
          filters:
            - StripPrefix=0

        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
          filters:
            - StripPrefix=0

        - id: claim-service
          uri: http://localhost:8083
          predicates:
            - Path=/claims/**
          filters:
            - StripPrefix=0
