spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      max-poll-records: 50

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      ack-mode: record

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
