spring:
  application:
    name: policy-service

  datasource:
    url: jdbc:postgresql://localhost:5432/policy_db
    username: postgres
    password: Postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
